language: java
jdk: 
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11

os:
  - linux

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.gradle

script:
  - ./gradlew build -s
  - mvn test -B
